# Generated by Django 5.2.1 on 2025-05-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_plan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='Title',
            field=models.TextField(default='', max_length=255),
        ),
    ]
