# Generated by Django 5.2.1 on 2025-05-12 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_plan_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='Title',
            new_name='title',
        ),
    ]
