# Generated by Django 5.2.1 on 2025-05-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_title_plan_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='plan',
            name='title',
        ),
    ]
