# Generated by Django 5.2.1 on 2025-05-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_gyminfo_remove_plan_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='gyminfo',
            name='homeDescription',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='gyminfo',
            name='name',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.TextField(default='Empty-name', max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
